name: Run manually specific spec

on:
  workflow_dispatch:
    inputs:
      specPath:
        type: choice
        required: true
        description: Choose spec path
        options:
          - api/api.spec.js
          - ui/main_page.spec.js

jobs:
  tests:
    name: Playwight spec run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - uses: microsoft/playwright-github-action@v1

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npx playwright install

      - name: Run tests
        run: SPEC=${{ github.event.inputs.specPath }} npm run test:spec

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results
          retention-days: 5

      - name: Get allure history
        uses: actions/checkout@v2
        if: ${{ always() }}
        continue-on-error: true
        with:
          ref: github-pages
          path: github-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: ${{ always() }}
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: github-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5

      - name: Deploy report to github pages branch
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: github-pages
          PUBLISH_DIR: allure-history
