name: Run manually tests

on:
  workflow_dispatch:

jobs:
  tests:
    name: Playwight tests run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npx playwright install

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 14

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results
          retention-days: 3

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: ${{ always() }}
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: github-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5

      - name: Deploy report to github pages branch
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: github-pages
          PUBLISH_DIR: allure-history
