name: Run manually specific spec

on:
  workflow_dispatch:
    inputs:
      specPath:
        type: choice
        required: true
        description: Choose spec path
        options:
          - api/api.spec.js
          - ui/main_page.spec.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
          cache: 'npm'
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install

  tests:
    name: Playwright run
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: SPEC=${{ github.event.inputs.specPath }} npm run test:spec

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 14

      - name: Get allure history
        uses: actions/checkout@v2
        if: ${{ always() }}
        continue-on-error: true
        with:
          ref: github-pages
          path: github-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: ${{ always() }}
        id: allure-report
        with:
          allure_results: allure-results
          github_pages: github-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Deploy report to github pages branch
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: github-pages
          PUBLISH_DIR: allure-history
